function createfigure(X1, Y1, S1, yvector1)
%CREATEFIGURE(X1,Y1,S1,YVECTOR1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 01-Feb-2012 04:18:40

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,...
    'YTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15],...
    'YGrid','on',...
    'XTick',[1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012],...
    'Position',[0.01953125 0.11 0.586718750000001 0.815]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1993 2012]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.210793213613785 15.741194019823]);
box(axes1,'on');
hold(axes1,'all');

% Create scatter
scatter(X1,Y1,S1,Y1,'MarkerFaceColor','flat','MarkerEdgeColor','none',...
    'Parent',axes1);

% Create axes
axes2 = axes('Parent',figure1,'YTick',[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15],...
    'Position',[0.6375 0.11 0.343750000000001 0.815]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[-54.6448087431693 640.437158469945]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.397660818713451 15.6023391812865]);
box(axes2,'on');
hold(axes2,'all');

% Create bar
bar(yvector1,'Horizontal','on','Parent',axes2);

